INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (1, 'Россия', null, '001.slava_zaitsev.maroussia.jpg', 'Амбра, бензоин, бобы тонка', 'Гвоздика, гелиотроп, жасмин', 'Альдегиды, ноты бергамота, персик', 'женский', 'MAROUSSIA', 'СЛАВА ЗАЙЦЕВ', 4090, 'Туалетная вода', '100', 1992);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (2, 'Россия', null, '002.slava_zaitsev.authentic_maroussia.jpg', 'Кедр, нарцисс', 'Дубовый мох, кориандр', 'Амбра', 'женский', 'AUTHENTIC MAROUSSIA', 'СЛАВА ЗАЙЦЕВ', 4889, 'Туалетная вода', '100', 1996);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (3, 'Россия', null, '003.slava_zaitsev.nikita.jpg', 'Амбра, ваниль, мускус', 'Жасмин', 'Имбирь, мандарин, перец', 'женский', 'NIKITA', 'СЛАВА ЗАЙЦЕВ', 7058, 'Туалетная вода', '30', 2007);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (4, 'Франция', null, '004.slava_zaitsev.velours_gourmand.jpg', 'Ветивер, пачули, тростниковый сахар', 'Какао, шоколад', 'Апельсин, лесной орех, миндаль', 'женский', 'VELOURS GOURMAND', 'СЛАВА ЗАЙЦЕВ', 10932, 'Парфюмерная вода', '100', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (5, 'Франция', null, '005.slava_zaitsev.balade_imaginaire.jpg', 'Дым, кожа, ладан, табак', 'Кипарис, шалфей', 'Ладан, полынь, розовый перец, ром', 'мужской', 'BALADE IMAGINAIRE', 'СЛАВА ЗАЙЦЕВ', 10932, 'Парфюмерная вода', '100', 2022);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (6, 'Франция', null, '006.slava_zaitsev.secret_du_style.jpg', 'Бобы тонка, мускус, пачули', 'Ирис, роза, жасмин', 'Грейпфрут, розовый перец', 'мужской', 'SECRET DU STYLE', 'СЛАВА ЗАЙЦЕВ', 10932, 'Парфюмерная вода', '100', 2022);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (7, 'Франция', null, '007.slava_zaitsev.soiree_parisienne.jpg', 'Амбра, дубовый мох, кедр, мускус', 'Ландыш, мускатный орех, фиалка', 'Грейпфрут, мандарин, розовый перец, шафран', 'женский', 'SOIREE PARISIENNE', 'СЛАВА ЗАЙЦЕВ', 10932, 'Парфюмерная вода', '100', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (8, 'Франция', null, '008.slava_zaitsev.blanc_eternel.jpg', 'Амбра, ветивер, сандаловое дерево', 'Лакричник, сосна', 'Кленовый сироп, полынь', 'женский', 'BLANC ETERNEL', 'СЛАВА ЗАЙЦЕВ', 10932, 'Парфюмерная вода', '100', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (9, 'Франция', null, '009.slava_zaitsev.parfum_de_soie.jpg', 'Амбра, кожа, ладан, уд', 'Кашемировое дерево, кумин, мускатный орех', 'Грейпфрут, роза', 'мужской', 'PARFUM DE SOIE', 'СЛАВА ЗАЙЦЕВ', 10932, 'Парфюмерная вода', '100', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (10, 'Россия', null, '010.cosmogony.proserpina.jpg', 'Бобы тонка, дерево гуаяк, дубовый мох', 'Гранат, дягиль, жасмин, илинг-иланг', 'Альдегиды, лимон, мандарин, ревень', 'женский', 'PROSERPINA', 'cosmogony', 9590, 'Парфюмерная вода', '65', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (11, 'Россия', null, '011.cosmogony.flaming_sky.jpg', 'Амбра, дубовый мох, кедр, мускус', 'Ваниль', 'Бессмертник, эвкалипт', 'женский', 'FLAMING SKY', 'cosmogony', 9590, 'Парфюмерная вода', '65', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (12, 'Россия', null, '012.cosmogony.morning_star.jpg', 'Амбра, мускус, пачули', 'Жасмин, красное вино, османтус', 'Ежевика, мандарин, слива', 'женский', 'MORNING STAR', 'cosmogony', 9590, 'Парфюмерная вода', '65', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (13, 'Россия', null, '013.cosmogony.solar_power.jpg', 'Амбра, бензоин, ваниль, дубовый мох', 'Герань, кофе, ландыш', 'Грейпфрут, кардамон, крыжовник', 'мужской', 'SOLAR POWER', 'cosmogony', 12090, 'Парфюмерная вода', '100', 2022);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (14, 'Россия', null, '014.cosmogony.other_side.jpg', 'Амбра, ветивер, дубовый мех', 'Альдегиды, ирис, личи, лотос, мимоза', 'Апельсин, дыня, кардамон, мята', 'мужской', 'OTHER SIDE', 'cosmogony', 11690, 'Парфюмерная вода', '100', 2022);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (15, 'Россия', null, '015.cosmogony.earth_core.jpg', 'Амбра, бобы тонка, кедр, пачули', 'Корень ириса, можжевельник, перец', 'Гальбанум, грейпфрут, лимон', 'мужской', 'EARTH CORE', 'cosmogony', 10690, 'Парфюмерная вода', '100', 2022);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (16, 'Россия', null, '016.cosmogony.phosphoros.jpg', 'Амбра, ветивер, мускус, ноты кожи', 'Давана, корица, османтус, роза', 'Мандарин, ноты бергамота', 'мужской', 'PHOSPHOROS', 'cosmogony', 12090, 'Парфюмерная вода', '100', 2022);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (17, 'Россия', null, '017.cosmogony.underworld.jpg', 'Амбра, мох, мускус, сандаловое дерево', 'Крыжовник, можжевельник, роза', 'Альдегиды, лимон, мандарин, ревень', 'мужской', 'UNDERWORLD', 'cosmogony', 12090, 'Парфюмерная вода', '100', 2022);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (18, 'Россия', null, '018.brokar_aromaty_prirody.antonovka_i_lugovaya_klubnika.jpg', 'Фруктовые ноты', 'Клубника', 'Яблоко', 'женский', 'Антоновка и луговая клубника', 'БРОКАРЪ АРОМАТЫ ПРИРОДЫ', 482, 'Туалетная вода', '100', 2017);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (19, 'Россия', null, '019.brokar_aromaty_prirody.siren_posle_dozhdya.jpg', 'Ваниль, гелиотроп, мед', 'Жасмин, ландыш, роза, сирень', 'Ноты бергамота, цветок миндаля', 'женский', 'Сирень после дождя', 'БРОКАРЪ АРОМАТЫ ПРИРОДЫ', 700, 'Туалетная вода', '100', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (20, 'Россия', null, '020.brokar_aromaty_prirody. chernaya_smorodina_i_myata.jpg', 'Фруктовые ноты', 'Мята', 'Черная смородина', 'женский', 'Черная смородина и мята', 'БРОКАРЪ АРОМАТЫ ПРИРОДЫ', 506, 'Туалетная вода', '100', 2017);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (21, 'Россия', null, '021.brokar_aromaty_prirody. lesnaya_malina_i_dushica.jpg', 'Дубовый мох, карамель, мускус', 'Фиалка, шиповник', 'Земляника, малина, ноты воды', 'женский', 'Лесная малина и душица', 'БРОКАРЪ АРОМАТЫ ПРИРОДЫ', 482, 'Туалетная вода', '100', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (22, 'Россия', null, '022.brocard_day_dreams.cristal_peony.jpg', 'Цветочные ноты', 'Зеленые листья, красные ягоды', 'Цитрусы', 'женский', 'CRISTAL PEONY', 'BROCARD DAY DREAMS', 413, 'Туалетная вода', '55', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (23, 'Россия', null, '023.brocard_day_dreams.silky_grass.jpg', 'Кардамон, матэ, табак', 'Жасмин', 'Апельсин, цедра лимона, черная смородина', 'женский', 'SILKY GRASS', 'BROCARD DAY DREAMS', 413, 'Туалетная вода', '55', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (24, 'Россия', null, '024.brocard_day_dreams.water_ivy.jpg', 'Жасмин, пион', 'Плющ', 'Ноты бергамота, персик', 'женский', 'WATER IVY', 'BROCARD DAY DREAMS', 413, 'Туалетная вода', '55', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (25, 'Россия', null, '025.brocard_color_feeling.green.jpg', 'Мускатный орех, озон, сандаловое дерево', 'Кедр, ноты бергамота, фиалка', 'Альдегиды, полынь', 'мужской', 'green', 'BROCARD COLOR FEELING', 520, 'Туалетная вода', '100', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (26, 'Россия', null, '026.brocard_color_feeling.blue.jpg', 'Мускатный шалфей, пачули, сандаловое дерево', 'Лаванда, морские ноты, нероли', 'Амбра, гелиотроп, мандарин', 'мужской', 'blue', 'BROCARD COLOR FEELING', 520, 'Туалетная вода', '100', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (27, 'Россия', null, '027.brocard_color_feeling.orange.jpg', 'Амбра, кедр, пачули', 'Апельсин, бархатцы, ирис, перец, роза', 'Манго, сандаловое дерево, физалис', 'мужской', 'orange', 'BROCARD COLOR FEELING', 520, 'Туалетная вода', '100', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (28, 'Франция', null, '028.brocard.dagger.jpg', 'Амбра, ваниль, мускус', 'Ветивер, пачули', 'Лаванда, лимон, ноты бергамота', 'мужской', 'Dagger', 'Brocard', 1890, 'Туалетная вода', '100', 2010);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (29, 'Россия', null, '029.brocard.original_12_scotch.jpg', 'Амбра, камфора, мускус, пачули', 'Мускатный орех, перец, роза', 'Апельсин, грейпфрут, лимон, мандарин', 'мужской', 'ORIGINAL 12 Scotch', 'Brocard', 990, 'Туалетная вода', '100', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (30, 'Россия', null, '030.brocard.perpetuum_man.jpg', 'Древесные ноты', 'Ноты воды', 'Пряные ноты', 'мужской', 'perpetuum MAN', 'Brocard', 1350, 'Парфюмерная вода', '100', 2010);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (31, 'Россия', null, '031.brocard.perpetuum_woman.jpg', 'Амбра, ваниль, мускус', 'Гелиотроп, жасмин, ландыш', 'Ананас, арбуз, груша, мандарин', 'женский', 'perpetuum WOMAN', 'Brocard', 1350, 'Парфюмерная вода', '100', 2012);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (32, 'Россия', null, '032.parfums_constantine.gentleman_1.jpg', 'Древесные ноты', 'Грейпфрут', 'Роза', 'мужской', 'GENTLEMAN 1', 'PARFUMS CONSTANTINE', 805, 'Туалетная вода', '100', 2015);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (33, 'Россия', null, '033.parfums_constantine.gentleman_6.jpg', 'Ваниль, ветивер, древесина оливы', 'Гвоздика, корица, красное дерево', 'Герань, дубовый мох, лимон, ноты бергамота', 'мужской', 'GENTLEMAN 6', 'PARFUMS CONSTANTINE', 855, 'Туалетная вода', '100', 2015);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (34, 'Россия', null, '034.parfums_constantine.gentleman_11.jpg', 'Амбра', 'Пачули', 'Морские ноты, цитрусы', 'мужской', 'GENTLEMAN 11', 'PARFUMS CONSTANTINE', 850, 'Туалетная вода', '100', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (35, 'Россия', null, '035.parfums_constantine.gentleman_13.jpg', 'Амбра, капучино, янтарь', 'Кардамон, мускатный орех, яблоко', 'Дыня, мята, черная смородина', 'мужской', 'GENTLEMAN 13', 'PARFUMS CONSTANTINE', 779, 'Туалетная вода', '100', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (36, 'Россия', null, '036.parfums_constantine.gentleman_17.jpg', 'Ветивер, кедр, ноты ладана', 'Давана, кардамон, перец', 'Гедион, грейпфрут, ноты бергамота', 'мужской', 'GENTLEMAN 17', 'PARFUMS CONSTANTINE', 782, 'Туалетная вода', '100', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (37, 'Россия', null, '037.parfums_constantine.mademoiselle_1.jpg', 'Цветочные ноты', 'Цветочные ноты', 'Цветочные ноты', 'женский', '1 MADEMOISELLE', 'PARFUMS CONSTANTINE', 724, 'Парфюмерная вода', '50', 2015);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (38, 'Россия', null, '038.parfums_constantine.mademoiselle_2.jpg', 'Амбра, кедр, мускус', 'Бамбук, жасмин, роза', 'Колокольчик, лимон, яблоко', 'женский', '2 MADEMOISELLE', 'PARFUMS CONSTANTINE', 752, 'Парфюмерная вода', '50', 2015);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (39, 'Россия', null, '039.parfums_constantine.mademoiselle_3.jpg', 'Мускус', 'Фруктовые ноты', 'Цветочные ноты', 'женский', '3 MADEMOISELLE', 'PARFUMS CONSTANTINE', 973, 'Парфюмерная вода', '50', 2015);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (40, 'Россия', null, '040.parfums_constantine.mademoiselle_4.jpg', 'Мускус', 'Древесные ноты', 'Цветочные ноты', 'женский', '4 MADEMOISELLE', 'PARFUMS CONSTANTINE', 688, 'Парфюмерная вода', '50', 2015);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (41, 'Россия', null, '041.parfums_constantine.new_york_perfume_one.jpg', 'Амбра, мускус, платан, шафран', 'Кедр, перец, тархун', 'Кардамон, лимон, ноты бергамота', 'мужской', 'NEW YORK PERFUME one', 'PARFUMS CONSTANTINE', 532, 'Туалетная вода', '90', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (42, 'Россия', null, '042.parfums_constantine.new_york_perfume_two.jpg', 'Кедр, пачули, сандаловое дерево', 'Лаванда, цветок апельсина', 'Лимон, мандарин, розовый перец', 'мужской', 'NEW YORK PERFUME two', 'PARFUMS CONSTANTINE', 524, 'Туалетная вода', '90', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (43, 'Россия', null, '043.parfums_constantine.new_york_perfume_three.jpg', 'Ваниль, древесина оливы, кедр', 'Гвоздика, корица, красное дерево', 'Герань, дубовый мох, лимон', 'мужской', 'NEW YORK PERFUME three', 'PARFUMS CONSTANTINE', 735, 'Туалетная вода', '90', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (44, 'Россия', null, '044.parfums_constantine.new_york_perfume_four.jpg', 'Амбра, древесные ноты', 'Капучино, кардамон, мускатный орех', 'Дыня, мята, ноты бергамота', 'мужской', 'NEW YORK PERFUME four', 'PARFUMS CONSTANTINE', 625, 'Туалетная вода', '90', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (45, 'Россия', null, '045.parfums_constantine.new_york_perfume_five.jpg', 'Древесные ноты, ноты кожи', 'Лаванда, манинка', 'Имбирь, мандарин, ноты бергамота', 'мужской', 'NEW YORK PERFUME five', 'PARFUMS CONSTANTINE', 578, 'Туалетная вода', '90', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (46, 'Россия', null, '046.megacosm.mars.jpg', 'Бобы тонка, кожаный аккорд, мускус', 'Чай, фрезия, красное яблоко', 'Бергамот, черная смородина, мандарин', 'мужской', 'Mars', 'MegaCosm', 12000, 'Парфюмерная вода', '100', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (47, 'Россия', null, '047.megacosm.moon.jpg', 'Мускус, кедр, сандал', 'Чай, кокосовая вода, ладан', 'Имбирь, кардамон', 'женский', 'Moon', 'MegaCosm', 12000, 'Парфюмерная вода', '100', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (48, 'Россия', null, '048.megacosm.earth.jpg', 'Амбра, лабданум, мускус', 'Гальбанум, нероли, ревень', 'Черная смородина, лимон, мандарин', 'женский', 'Earth', 'MegaCosm', 12000, 'Парфюмерная вода', '100', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (49, 'Россия', null, '049.fruttissimo.inner_sun.jpg', 'Кедр, мускус, сандаловое дерево', 'Абрикос, груша, нектарин, персик', 'Апельсин, кумкват, лайм, лимон', 'женский', 'Inner Sun', 'Fruttissimo', 411, 'Туалетная вода', '35', 2016);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (50, 'Россия', null, '050.fruttissimo.sparkling_strawberry.jpg', 'Мята', 'Лайм', 'Клубника', 'женский', 'Sparkling Strawberry', 'Fruttissimo', 387, 'Туалетная вода', '35', 2016);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (51, 'Россия', null, '051.fruttissimo.thai_smoothie.jpg', 'Кокосовое молоко, манго, тростниковый сахар', 'Ананас, личи', 'Апельсин', 'женский', 'Thai Smoothie', 'Fruttissimo', 490, 'Туалетная вода', '35', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (52, 'Россия', null, '052.fruttissimo.perry.jpg', 'Груша', 'Груша', 'Груша', 'женский', 'Perry', 'Fruttissimo', 411, 'Туалетная вода', '35', 2016);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (53, 'Россия', null, '053.anna_zworykina.secret_dreams.jpg', 'Агар, дерево гуаяк, имбирь', 'Бессмертник, кардамон, коньяк', 'Гвоздика, кумин, можжевельник', 'женский', 'SECRET DREAMS', 'ANNA ZWORYKINA', 9850, 'Парфюмерная вода', '15', 2012);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (54, 'Россия', null, '054.anna_zworykina.verdigris.jpg', 'Бобы тонка, ветивер, дягиль', 'Лаванда, можжевельник, нероли', 'Гальбанум, лимон, ноты бергамота', 'женский', 'VERDIGRIS', 'ANNA ZWORYKINA', 9850, 'Парфюмерная вода', '15', 2012);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (55, 'Россия', null, '055.anna_zworykina.golden_lavender.jpg', 'Ваниль, дягиль, кардамон, корица', 'Жасмин, иланг-иланг, лаванда', 'Кассия, лилия, лимон, ноты бергамота', 'женский', 'GOLDEN LAVENDER', 'ANNA ZWORYKINA', 9850, 'Парфюмерная вода', '15', 2012);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (56, 'Россия', null, '056.anna_zworykina.nigredo.jpg', 'Бальзам, зеленые ноты, ирис', 'Ветивер, ноты ладана, пачули', 'Абсент, османтус, элеми', 'женский', 'NIGREDO', 'ANNA ZWORYKINA', 9850, 'Парфюмерная вода', '15', 2012);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (57, 'Россия', null, '057.anna_zworykina.vtoraya_kozha.jpg', 'Ваниль, гибискус, дубовый мох', 'Жасмин, илинг-иланг, кассия', 'Бессмертник, гвоздика. ноты бергамота', 'женский', 'ВТОРАЯ КОЖА', 'ANNA ZWORYKINA', 9850, 'Парфюмерная вода', '15', 2013);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (58, 'Россия', null, '058.lab_fragrance.secret.jpg', 'Амбра, ветивер, мускус', 'Кедр, фиалка', 'Апельсин, ноты бергамота', 'женский', 'SECRET', 'LAB FRAGRANCE', 5074, 'Парфюмерная вода', '50', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (59, 'Россия', null, '059.lab_fragrance.arabian_night.jpg', 'Бензоин, ваниль, мускус', 'Кедр, лабданум, пачули', 'Имбирь, карамель, кардамон', 'женский', 'ARABIAN NIGHT', 'LAB FRAGRANCE', 6358, 'Парфюмерная вода', '50', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (60, 'Россия', null, '060.lab_fragrance.adventurer.jpg', 'Амбра, дубовый мох, мускус', 'Жасмин, кедр, пачули, роза', 'Ноты бергамота, черная смородина, яблоко', 'мужской', 'ADVENTURER', 'LAB FRAGRANCE', 5648, 'Парфюмерная вода', '50', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (61, 'Германия', null, '061.s_oliver_pure_sense.women.jpg', 'Амброксан, древесные ноты, мускус', 'Бамбук, магнолия, роза', 'Ананас, лимон, ноты бергамота', 'женский', 'WOMEN', 's.Oliver PURE SENSE', 3355, 'Туалетная вода', '50', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (62, 'Германия', null, '062.s_oliver_pure_sense.men.jpg', 'Кедр, пачули, сандаловое дерево', 'Дерево хиноки, лаванда', 'Апельсин, грейпфрут, яблоко', 'мужской', 'MEN', 's.Oliver PURE SENSE', 3355, 'Туалетная вода', '50', 2021);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (63, 'Россия', null, '063.sergio_nero.pandora.jpg', 'Дерево лимона, мускус, сандаловое дерево', 'Арбуз, жасмин, цикламен', 'Киви, перец, ревень', 'женский', 'PANDORA', 'Sergio Nero', 1190, 'Туалетная вода', '50', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (64, 'Россия', null, '064.sergio_nero.pandora_elegance.jpg', 'Амбра, кедр, мускус', 'Зеленый чай, османтус, персик', 'Глициния, лимон', 'женский', 'PANDORA ELEGANCE', 'Sergio Nero', 1290, 'Туалетная вода', '50', 2019);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (65, 'Иордания', null, '065.zeitun.white_musk_attar.jpg', 'Белый мускус', 'Сандал', 'Цветочные ноты', 'женский', 'White Musk Attar', 'Zeitun', 1700, 'Парфюмерная вода', '10', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (66, 'Иордания', null, '066.zeitun.majmua_attar.jpg', 'Древесные ноты', 'Сандал', 'Ветивер', 'женский', 'Majmua Attar', 'Zeitun', 1700, 'Парфюмерная вода', '10', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (67, 'Иордания', null, '067.zeitun.shamama_attar.jpg', 'Морской аккорд, сандал, трава', 'Дым, мята, мед', 'Цветочные ноты', 'женский', 'Shamama Attar', 'Zeitun', 1700, 'Парфюмерная вода', '10', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (68, 'Иордания', null, '068.zeitun.black_musk_attar.jpg', 'Черный мускус', 'Сандал', 'Древесные ноты', 'женский', 'Black Musk Attar', 'Zeitun', 1700, 'Парфюмерная вода', '10', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (69, 'Россия', null, '069.magma.rosedry.jpg', 'Амбра, ветивер, дерево гуаяк', 'Гвоздика, пион, роза', 'Ананас, грейпрут, груша', 'женский', 'ROSEDRY', 'MAGMA', 13490, 'Парфюмерная вода', '30', 2019);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (70, 'Россия', null, '070.magma.dopamine.jpg', 'Амбра, массойя, пачули', 'Перец, слива', 'Лимон, фундук, черная смородина', 'женский', 'DOPAMINE', 'MAGMA', 13490, 'Парфюмерная вода', '30', 2017);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (71, 'Россия', null, '071.magma.boutique.jpg', 'Бензоин, ваниль, дубовый мох', 'Ландыш, нарцисс, ноты земли', 'Жасмин, ноты бергамота, перец', 'женский', 'BOUTIQUE', 'MAGMA', 13490, 'Парфюмерная вода', '30', 2017);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (72, 'Россия', null, '072.magma.chocoholic.jpg', 'Кедр, мускус, олибанум', 'Бензоин, ваниль, какао, пачули', 'Ирис, манго, мандарин', 'женский', 'CHOCOHOLIC', 'MAGMA', 13490, 'Парфюмерная вода', '30', 2017);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (73, 'Россия', null, '073.natura_siberica.nuit_en_siberie.jpg', 'Элеми, ладан, пачули', 'Белый перец, можжевельник, черный перец', 'Бергамот, Кардамон, Танжерин', 'мужской', 'NUIT EN SIBERIE', 'NATURA SIBERICA', 6000, 'Парфюмерная вода', '100', 2017);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (74, 'Россия', null, '074.natura_siberica.gold_of_tuva.jpg', 'Кедр, ладан, мускус', 'Чай, молоко, специи', 'Бергамот, камфора, кардамон', 'женский', 'GOLD OF TUVA', 'NATURA SIBERICA', 6000, 'Парфюмерная вода', '100', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (75, 'Россия', null, '075.natura_siberica.siberie_mon_amour.jpg', 'Амбра, мускус', 'Мята, розмарин', 'Полынь (артемизия). лемонграсс, черный перец', 'женский', 'SIBERIE MON AMOUR', 'NATURA SIBERICA', 6000, 'Парфюмерная вода', '100', 2017);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (76, 'Россия', null, '076.natura_siberica.danse_du_shaman.jpg', 'Амбра, кедр атласский, ладан, пачули', 'Дым, сосна', 'Бергамот, элеми, гваяковое дерево', 'мужской', 'DANSE DU SHAMAN', 'NATURA SIBERICA', 6000, 'Парфюмерная вода', '100', 2017);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (77, 'Россия', null, '077.natura_siberica.safran_de_siberie.jpg', 'Кипарис, пачули', 'Мускус, розовый перец, ветивер', 'Бергамот, пион, роза', 'женский', 'SAFRAN DE SIBERIE', 'NATURA SIBERICA', 6000, 'Парфюмерная вода', '100', 2017);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (78, 'Россия', null, '078.ciel.pour_femme.jpg', 'Бензоин, бобы тонка, кашмеран', 'Апельсиновый цвет, чернослив, фрезия', 'Черная смородина, яблоко, лимон', 'женский', 'Pour Femme', 'CIEL', 3100, 'Парфюмерная вода', '50', 2012);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (79, 'Россия', null, '079.ciel.lui.jpg', 'Пачули, сандал, ветивер', 'Фиалка, герань, ирис', 'Бергамот, кипарис, лаванда', 'мужской', 'LUI', 'CIEL', 1400, 'Парфюмерная вода', '50', 2016);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (80, 'Россия', null, '080.ciel.crash_marine.jpg', 'Амбра, кедр, мускус', 'Кипарис, розмарин, сосна', 'Альдегиды, лимон, акватический аккорд', 'мужской', 'CRASH marine', 'CIEL', 2100, 'Парфюмерная вода', '100', 2012);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (81, 'Россия', null, '081.sergio_nero.instant_desire_dream.jpg', 'Мускус', 'Сладкие ноты', 'Фруктовые ноты', 'женский', 'INSTANT DESIRE DREAM', 'Sergio Nero', 1390, 'Парфюмерная вода', '35', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (82, 'Россия', null, '082.sergio_nero.admiral.jpg', 'Древесные ноты', 'Кедр, нероли, перец', 'Мандарин, морские ноты', 'мужской', 'Адмиралъ', 'Sergio Nero', 1390, 'Туалетная вода', '100', 2012);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (83, 'Россия', null, '083.sergio_nero.pour_homme.jpg', 'Мед', 'Гвоздика, кориандр, шалфей', 'Коньяк, табак', 'мужской', 'POUR HOMME', 'Sergio Nero', 2490, 'Парфюмерная вода', '50', 2006);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (84, 'Россия', null, '084.sergio_nero.vsop_deep_blue.jpg', 'Ветивер, кедр', 'Кардамон, лаванда, перец', 'Грейпрут, ноты бергамота', 'мужской', 'VSOP DEEP BLUE', 'Sergio Nero', 1390, 'Туалетная вода', '95', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (85, 'Великобритания', null, '085.rouge_bunny_rouge.incantation.jpg', 'Ветивер, кедр, мускус, пчелиный воск', 'Кардамон, кориандр, цветок апельсина', 'Зеленый чай, листья инжира, цитрусы', 'женский', 'INCANTATION', 'ROUGE BUNNY ROUGE', 16090, 'Парфюмерная вода', '50', 2013);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (86, 'Великобритания', null, '086.rouge_bunny_rouge.arcane.jpg', 'Кедр, мускус, пачули, сандаловое дерево', 'Амбра, ноты ладана, цистус', 'Ваниль, специи, шафран', 'женский', 'ARCANE', 'ROUGE BUNNY ROUGE', 7313, 'Парфюмерная вода', '50', 2016);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (87, 'Великобритания', null, '087.rouge_bunny_rouge.cynefin.jpg', 'Амбра, древесный аккорд, мускус', 'Ландыш, лаванда, лист фиалки', 'Дягиль (ангелика), давана', 'мужской', 'CYNEFIN', 'ROUGE BUNNY ROUGE', 7890, 'Парфюмерная вода', '50', 2013);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (88, 'Оман', null, '088.amouage.ciel.jpg', 'Амбра, кедр, мускус, сандаловое дерево', 'Водяная лилия, жасмин, роза', 'Гардения, листья фиалки, цикламен', 'женский', 'CIEL', 'AMOUAGE', 19890, 'Парфюмерная вода', '50', 2003);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (89, 'Оман', null, '089.amouage.reflection.jpg', 'Ветивер, кедр, пачули', 'Жасмин, корень фиалки, нероли', 'Злаки, перец, розмарин', 'мужской', 'REFLECTION', 'AMOUAGE', 18690, 'Парфюмерная вода', '50', 2007);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (90, 'Оман', null, '090.amouage.lyric.jpg', 'Ваниль, мускус, сандаловое дерево', 'Гальбанум, имбирь, мускатный орех', 'Лайм, ноты бергамота', 'мужской', 'LYRIC', 'AMOUAGE', 19190, 'Парфюмерная вода', '50', 2008);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (91, 'Россия', null, '091.nouvelle_etoile.kuznetsky_most.jpg', 'Амбра, древесные ноты, табак', 'Иланг-иланг, ирис, кориандр', 'Апельсин, ноты бергамота', 'женский', 'KUZNETSKY MOST', 'NOUVELLE ETOILE', 1490, 'Парфюмерная вода', '30', 2004);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (92, 'Россия', null, '092.nouvelle_etoile.kuznetsky_most_pour_homme.jpg', 'Кедр, мускус', 'Ананас', 'Грейпфрут, черная смородина', 'мужской', 'KUZNETSKY MOST POUR HOMME', 'NOUVELLE ETOILE', 2190, 'Туалетная вода', '100', 2005);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (93, 'Россия', null, '093.nouvelle_etoile.kuznetsky_most_le_soir.jpg', 'Амбра, ирис, кедр, мускус', 'Жасмин, ландыш, мимоза, роза', 'Ноты бергамота, фруктовые ноты, черная смородина', 'женский', 'KUZNETSKY MOST LE SOIR', 'NOUVELLE ETOILE', 1490, 'Парфюмерная вода', '30', 2005);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (94, 'Россия', null, '094.nouvelle_etoile.galion_dor.jpg', 'Амбра, мускус', 'Пряные ноты', 'Цитрусы', 'мужской', 'GALION dor', 'NOUVELLE ETOILE', 2390, 'Туалетная вода', '100', 2009);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (95, 'Россия', null, '095.nouvelle_etoile.forward.jpg', 'Амбра', 'Кедр, мох', 'Ноты бергамота, черная смородина, яблоко', 'мужской', 'FORWARD', 'NOUVELLE ETOILE', 1490, 'Туалетная вода', '100', 2001);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (96, 'Россия', null, '096.nouvelle_etoile.la_belle_de_russie.jpg', 'Амбра, ваниль, кедр', 'Абрикос, жасмин, ирис', 'Гвоздика, лотос, черная смородина', 'женский', 'LA BELLE DE RUSSIE', 'NOUVELLE ETOILE', 1090, 'Парфюмерная вода', '16', 2004);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (97, 'Россия', null, '097.novaya_zarya.symbol.jpg', 'Ваниль, дерево гуаяк, каштан', 'Ананас, дыня, корица', 'Кардамон, листья фиалки, мята', 'мужской', 'SYMBOL', 'НОВАЯ ЗАРЯ', 2190, 'Туалетная вода', '100', 2019);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (98, 'Россия', null, '098.novaya_zarya.patchouli_magique.jpg', 'Ваниль, мускус', 'Ладанник, ноты ладана, пачули', 'Лимон, ноты бергамота', 'женский', 'PATCHOULI MAGIQUE', 'НОВАЯ ЗАРЯ', 1690, 'Парфюмерная вода', '30', 2002);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (99, 'Россия', null, '099.novaya_zarya.krasnaya_moskva_layt.jpg', 'Бобы тонка, ваниль', 'Жасмин, роза, тубероза', 'Гвоздика, иланг-иланг, ноты бергамота', 'женский', 'КРАСНАЯ МОСКВА ЛАЙТ', 'НОВАЯ ЗАРЯ', 1890, 'Парфюмерная вода', '50', 2018);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (100, 'Россия', null, '100.novaya_zarya.ma_chance.jpg', 'Персик', 'Жасмин, иланг-иланг, нероли', 'Ноты воды', 'женский', 'MA CHANCE', 'НОВАЯ ЗАРЯ', 1290, 'Парфюмерная вода', '50', 2022);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (101, 'Россия', null, '101.vikon_de_paris.energy_sport.jpg', 'Амбра, ваниль', 'Герань, роза', 'Ноты бергамота', 'мужской', 'ENERGY SPORT', 'VIKON DE PARIS', 2290, 'Туалетная вода', '100', 2008);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (102, 'Россия', null, '102.vikon_de_paris.bleu_fonce.jpg', 'Ветивер, кедр, сандаловое дерево', 'Анис, имбирь, мускатный орех', 'Грейпрут, лимон, ноты бергамота', 'мужской', 'BLEU FONCE', 'VIKON DE PARIS', 1790, 'Туалетная вода', '80', 2012);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (103, 'Россия', null, '103.alan_bray.l_homme_seduction.jpg', 'Дубовый мох, кедр, мускус', 'Жасмин, кардамон', 'Ноты бергамота, черная смородина', 'мужской', 'L HOMME seduction', 'ALAN BRAY', 2190, 'Туалетная вода', '100', 2014);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (104, 'Россия', null, '104.alan_bray.l_homme_adventure.jpg', 'Гвоздика, дубовый мох, корица', 'Ветивер, кедр, сандаловое дерево', 'Герань, ноты бергамота, яблоко', 'мужской', 'L HOMME adventure', 'ALAN BRAY', 2190, 'Туалетная вода', '100', 2014);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (105, 'Россия', null, '105.alan_bray.wood_land.jpg', 'Ветивер, кедр', 'Яблоко', 'Цитрусы', 'мужской', 'WOOD LAND', 'ALAN BRAY', 2390, 'Туалетная вода', '100', 2019);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (106, 'Россия', null, '106.alan_bray.high_land.jpg', 'Корица, перец', 'Мартини', 'Лайм, яблоко', 'мужской', 'HIGH LAND', 'ALAN BRAY', 2290, 'Туалетная вода', '100', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (107, 'Россия', null, '107.alan_bray.u_different_unique.jpg', 'Амбра, ваниль, кедр, пачули', 'Герань, лаванда, шалфей', 'Корица, ноты бергамота, яблоко', 'мужской', 'U DIFFERENT UNIQUE', 'ALAN BRAY', 2590, 'Туалетная вода', '100', 2020);
INSERT INTO perfumes (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year) VALUES (108, 'Россия', null, '108.alan_bray.u_different_genesis.jpg', 'Мускус, сандаловое дерево', 'Жасмин, ноты кожи, роза', 'Лимон, морские ноты', 'мужской', 'U DIFFERENT GENESIS', 'ALAN BRAY', 1590, 'Туалетная вода', '100', 2020);

















